name: Build and Push Docker Image

on:
  push:
    branches:
      - development  # Change if your default branch is different

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build Angular Project
        run: |
          npm install -g @angular/cli
          npm install
          ng build --configuration=production

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ nkumar1988 }}
          password: ${{ Sbi@2399 }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: NIC0197/angular-poc:latest  # Change to your Docker Hub repo
